site_name: Numbers 101
site_author: sweetser@alum.mit.edu
copyright: 2015, Doug Sweetser, all rights reserved.
pages:
- [index.md, Static numbers, Static Numbers]
- [static/plane_intro.md, Static numbers, Static numbers in a plane]
- [static/horizontal.md, Static numbers, Add horizontally]
- [static/vertical.md, Static numbers, Add vertically]
- [static/diagonal.md, Static numbers, Add diagonally]
- [static/plane_summary.md, Static numbers, Complex numbers as the plane]
- [animated/animated.md, Animated numbers, Animated numbers]
- [animated/time.md, Animated numbers, Move only in time]
- [animated/space.md, Animated numbers, Big only briefly]
- [animated/motion.md, Animated numbers, Constant motion]
- [animated/complex_animation.md, Animated numbers, Complex numbers as animations]
- [space-time/space-time.md, Space-time numbers, Space-time numbers]
- [space-time/time.md, Space-time numbers, Move only in time]
- [space-time/space.md, Space-time numbers, Big only briefly]
- [space-time/motion.md, Space-time numbers, Constant motion]
- [space-time/space_time_animations.md, Space-time numbers, Space-time numbers as animations]
- [qft.md, Super collider numbers]
- [about/summary.md, About, Summary]
- [about/technical_summary.md, About, Technical summary]
- [about/how_done.md, About, How this was done]
- [about/professional.md, About, Professional sketch]
- [about/personal.md, About, Personal sketch]
- [about/contact.md, About, Contact]
- [about/tip_jar.md, About, Tip jar]
theme_dir: spacelab-mod
